### Variables
@HostUrl = http://localhost:5000

### Scan Assets - Scan internal assets directory (ASSETS_PATH)
GET {{HostUrl}}/api/assets/scan
Accept: application/json

###

### Scan Assets Stream - Stream scanning progress for internal assets directory
GET {{HostUrl}}/api/assets/scan/stream
Accept: application/json

###

